name: Setup BLE GATT Device Development Environment

steps:
  - name: Initialize git submodules
    run: git submodule update --init --recursive

  - name: Install Python dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -e ".[dev]"

  - name: Verify essential setup
    run: |
      test -f "bluetooth_sig/assigned_numbers/uuids/service_uuids.yaml" || exit 1
      python -c "import ble_gatt_device.gatt.uuid_registry" || exit 1