"""Data types for Bluetooth SIG standards."""

from __future__ import annotations

from .advertising import (
    AdvertisementData,
    AdvertisingData,
    AdvertisingDataInfo,
    AdvertisingDataStructures,
    AuxiliaryPointer,
    BLEAdvertisingFlags,
    BLEAdvertisingPDU,
    BLEExtendedHeader,
    ConnectionIntervalRange,
    CoreAdvertisingData,
    CTEInfo,
    CTEType,
    DeviceProperties,
    DirectedAdvertisingData,
    ExtendedAdvertisingData,
    ExtendedHeaderFlags,
    LEFeatureBits,
    LEFeatures,
    LocationAndSensingData,
    MeshAndBroadcastData,
    OOBSecurityData,
    PDUHeaderFlags,
    PDULayout,
    PDUType,
    PHYType,
    SecurityData,
    SyncInfo,
)
from .alert import (
    ALERT_CATEGORY_DEFINED_MAX,
    ALERT_CATEGORY_RESERVED_MAX,
    ALERT_CATEGORY_RESERVED_MIN,
    ALERT_CATEGORY_SERVICE_SPECIFIC_MIN,
    ALERT_COMMAND_MAX,
    ALERT_TEXT_MAX_LENGTH,
    UNREAD_COUNT_MAX,
    UNREAD_COUNT_MORE_THAN_MAX,
    AlertCategoryBitMask,
    AlertCategoryID,
    AlertNotificationCommandID,
)
from .appearance import AppearanceData
from .base_types import SIGInfo
from .battery import BatteryChargeLevel, BatteryChargeState, BatteryChargingType, BatteryFaultReason
from .company import CompanyIdentifier, ManufacturerData
from .context import CharacteristicContext, DeviceInfo
from .data_types import (
    CharacteristicInfo,
    DateData,
    ParseFieldError,
    ServiceInfo,
    ValidationAccumulator,
    ValidationResult,
)
from .ead import (
    EAD_ADDRESS_SIZE,
    EAD_IV_SIZE,
    EAD_MIC_SIZE,
    EAD_MIN_SIZE,
    EAD_NONCE_SIZE,
    EAD_RANDOMIZER_SIZE,
    EAD_SESSION_KEY_SIZE,
    EADDecryptResult,
    EADError,
    EADKeyMaterial,
    EncryptedAdvertisingData,
)
from .location import PositionStatus
from .protocols import CharacteristicProtocol
from .registry.ad_types import AdTypeInfo
from .registry.appearance_info import AppearanceInfo
from .registry.class_of_device import ClassOfDeviceInfo
from .registry.descriptor_types import DescriptorData, DescriptorInfo
from .registry.uri_schemes import UriSchemeInfo
from .special_values import SpecialValueResult, SpecialValueRule
from .units import (
    AngleUnit,
    ConcentrationUnit,
    ElectricalUnit,
    GlucoseConcentrationUnit,
    HeightUnit,
    LengthUnit,
    MeasurementSystem,
    PercentageUnit,
    PhysicalUnit,
    PressureUnit,
    SoundUnit,
    SpecialValueType,
    TemperatureUnit,
    WeightUnit,
    classify_special_value,
)
from .uri import URIData

# Device-related types are imported from device_types module to avoid cyclic imports
# Import them directly: from bluetooth_sig.types.device_types import DeviceService, DeviceEncryption

# Device-related types are imported from device_types module to avoid cyclic imports
# Import them directly: from bluetooth_sig.types.device_types import DeviceService, DeviceEncryption

__all__ = [
    "ALERT_CATEGORY_DEFINED_MAX",
    "ALERT_CATEGORY_RESERVED_MAX",
    "ALERT_CATEGORY_RESERVED_MIN",
    "ALERT_CATEGORY_SERVICE_SPECIFIC_MIN",
    "ALERT_COMMAND_MAX",
    "ALERT_TEXT_MAX_LENGTH",
    "EAD_ADDRESS_SIZE",
    "EAD_IV_SIZE",
    "EAD_MIC_SIZE",
    "EAD_MIN_SIZE",
    "EAD_NONCE_SIZE",
    "EAD_RANDOMIZER_SIZE",
    "EAD_SESSION_KEY_SIZE",
    "UNREAD_COUNT_MAX",
    "UNREAD_COUNT_MORE_THAN_MAX",
    "AdTypeInfo",
    "AdvertisementData",
    "AdvertisingData",
    "AdvertisingDataInfo",
    "AdvertisingDataStructures",
    "AlertCategoryBitMask",
    "AlertCategoryID",
    "AlertNotificationCommandID",
    "AngleUnit",
    "AppearanceData",
    "AppearanceInfo",
    "AuxiliaryPointer",
    "BLEAdvertisingFlags",
    "BLEAdvertisingPDU",
    "BLEExtendedHeader",
    "BatteryChargeLevel",
    "BatteryChargeState",
    "BatteryChargingType",
    "BatteryFaultReason",
    "CTEInfo",
    "CTEType",
    "CharacteristicContext",
    "CharacteristicInfo",
    "CharacteristicProtocol",
    "ClassOfDeviceInfo",
    "CompanyIdentifier",
    "ConcentrationUnit",
    "ConnectionIntervalRange",
    "CoreAdvertisingData",
    "DateData",
    "DescriptorData",
    "DescriptorInfo",
    "DeviceInfo",
    "DeviceProperties",
    "DirectedAdvertisingData",
    "EADDecryptResult",
    "EADError",
    "EADKeyMaterial",
    "ElectricalUnit",
    "EncryptedAdvertisingData",
    "ExtendedAdvertisingData",
    "ExtendedHeaderFlags",
    "GlucoseConcentrationUnit",
    "HeightUnit",
    "LEFeatureBits",
    "LEFeatures",
    "LengthUnit",
    "LocationAndSensingData",
    "ManufacturerData",
    "MeasurementSystem",
    "MeshAndBroadcastData",
    "OOBSecurityData",
    "PDUHeaderFlags",
    "PDULayout",
    "PDUType",
    "PHYType",
    "ParseFieldError",
    "PercentageUnit",
    "PhysicalUnit",
    "PositionStatus",
    "PressureUnit",
    "SIGInfo",
    "SecurityData",
    "ServiceInfo",
    "SoundUnit",
    "SpecialValueResult",
    "SpecialValueRule",
    "SpecialValueType",
    "SyncInfo",
    "TemperatureUnit",
    "URIData",
    "UriSchemeInfo",
    "ValidationAccumulator",
    "ValidationResult",
    "WeightUnit",
    "classify_special_value",
]
