"""Generated lazy export map for GATT descriptors. Do not edit by hand."""

from __future__ import annotations

LAZY_EXPORT_MAP: dict[str, str] = {
    "CCCDData": "bluetooth_sig.gatt.descriptors.cccd",
    "CCCDDescriptor": "bluetooth_sig.gatt.descriptors.cccd",
    "CCCDFlags": "bluetooth_sig.gatt.descriptors.cccd",
    "CharacteristicAggregateFormatData": "bluetooth_sig.gatt.descriptors.characteristic_aggregate_format",
    "CharacteristicAggregateFormatDescriptor": "bluetooth_sig.gatt.descriptors.characteristic_aggregate_format",
    "CharacteristicExtendedPropertiesData": "bluetooth_sig.gatt.descriptors.characteristic_extended_properties",
    "CharacteristicExtendedPropertiesDescriptor": "bluetooth_sig.gatt.descriptors.characteristic_extended_properties",
    "CharacteristicPresentationFormatData": "bluetooth_sig.gatt.descriptors.characteristic_presentation_format",
    "CharacteristicPresentationFormatDescriptor": "bluetooth_sig.gatt.descriptors.characteristic_presentation_format",
    "CharacteristicUserDescriptionData": "bluetooth_sig.gatt.descriptors.characteristic_user_description",
    "CharacteristicUserDescriptionDescriptor": "bluetooth_sig.gatt.descriptors.characteristic_user_description",
    "CompleteBREDRTransportBlockDataData": "bluetooth_sig.gatt.descriptors.complete_br_edr_transport_block_data",
    "CompleteBREDRTransportBlockDataDescriptor": "bluetooth_sig.gatt.descriptors.complete_br_edr_transport_block_data",
    "ESCFlags": "bluetooth_sig.gatt.descriptors.environmental_sensing_configuration",
    "EnvironmentalSensingConfigurationData": "bluetooth_sig.gatt.descriptors.environmental_sensing_configuration",
    "EnvironmentalSensingConfigurationDescriptor": "bluetooth_sig.gatt.descriptors.environmental_sensing_configuration",
    "EnvironmentalSensingMeasurementData": "bluetooth_sig.gatt.descriptors.environmental_sensing_measurement",
    "EnvironmentalSensingMeasurementDescriptor": "bluetooth_sig.gatt.descriptors.environmental_sensing_measurement",
    "EnvironmentalSensingTriggerSettingData": "bluetooth_sig.gatt.descriptors.environmental_sensing_trigger_setting",
    "EnvironmentalSensingTriggerSettingDescriptor": "bluetooth_sig.gatt.descriptors.environmental_sensing_trigger_setting",
    "ExtendedPropertiesFlags": "bluetooth_sig.gatt.descriptors.characteristic_extended_properties",
    "ExternalReportReferenceData": "bluetooth_sig.gatt.descriptors.external_report_reference",
    "ExternalReportReferenceDescriptor": "bluetooth_sig.gatt.descriptors.external_report_reference",
    "FormatNamespace": "bluetooth_sig.gatt.descriptors.characteristic_presentation_format",
    "FormatType": "bluetooth_sig.gatt.descriptors.characteristic_presentation_format",
    "IMDTriggerSettingData": "bluetooth_sig.gatt.descriptors.imd_trigger_setting",
    "IMDTriggerSettingDescriptor": "bluetooth_sig.gatt.descriptors.imd_trigger_setting",
    "ManufacturerLimitsData": "bluetooth_sig.gatt.descriptors.manufacturer_limits",
    "ManufacturerLimitsDescriptor": "bluetooth_sig.gatt.descriptors.manufacturer_limits",
    "MeasurementDescriptionData": "bluetooth_sig.gatt.descriptors.measurement_description",
    "MeasurementDescriptionDescriptor": "bluetooth_sig.gatt.descriptors.measurement_description",
    "NumberOfDigitalsData": "bluetooth_sig.gatt.descriptors.number_of_digitals",
    "NumberOfDigitalsDescriptor": "bluetooth_sig.gatt.descriptors.number_of_digitals",
    "ObservationScheduleData": "bluetooth_sig.gatt.descriptors.observation_schedule",
    "ObservationScheduleDescriptor": "bluetooth_sig.gatt.descriptors.observation_schedule",
    "ProcessTolerancesData": "bluetooth_sig.gatt.descriptors.process_tolerances",
    "ProcessTolerancesDescriptor": "bluetooth_sig.gatt.descriptors.process_tolerances",
    "ReportReferenceData": "bluetooth_sig.gatt.descriptors.report_reference",
    "ReportReferenceDescriptor": "bluetooth_sig.gatt.descriptors.report_reference",
    "ReportType": "bluetooth_sig.gatt.descriptors.report_reference",
    "SCCDData": "bluetooth_sig.gatt.descriptors.server_characteristic_configuration",
    "SCCDFlags": "bluetooth_sig.gatt.descriptors.server_characteristic_configuration",
    "ServerCharacteristicConfigurationDescriptor": "bluetooth_sig.gatt.descriptors.server_characteristic_configuration",
    "TimeTriggerSettingData": "bluetooth_sig.gatt.descriptors.time_trigger_setting",
    "TimeTriggerSettingDescriptor": "bluetooth_sig.gatt.descriptors.time_trigger_setting",
    "TriggerCondition": "bluetooth_sig.gatt.descriptors.value_trigger_setting",
    "ValidRangeAndAccuracyData": "bluetooth_sig.gatt.descriptors.valid_range_and_accuracy",
    "ValidRangeAndAccuracyDescriptor": "bluetooth_sig.gatt.descriptors.valid_range_and_accuracy",
    "ValidRangeData": "bluetooth_sig.gatt.descriptors.valid_range",
    "ValidRangeDescriptor": "bluetooth_sig.gatt.descriptors.valid_range",
    "ValueTriggerSettingData": "bluetooth_sig.gatt.descriptors.value_trigger_setting",
    "ValueTriggerSettingDescriptor": "bluetooth_sig.gatt.descriptors.value_trigger_setting",
}

LAZY_EXPORT_NAMES: tuple[str, ...] = (
    "CCCDData",
    "CCCDDescriptor",
    "CCCDFlags",
    "CharacteristicAggregateFormatData",
    "CharacteristicAggregateFormatDescriptor",
    "CharacteristicExtendedPropertiesData",
    "CharacteristicExtendedPropertiesDescriptor",
    "CharacteristicPresentationFormatData",
    "CharacteristicPresentationFormatDescriptor",
    "CharacteristicUserDescriptionData",
    "CharacteristicUserDescriptionDescriptor",
    "CompleteBREDRTransportBlockDataData",
    "CompleteBREDRTransportBlockDataDescriptor",
    "ESCFlags",
    "EnvironmentalSensingConfigurationData",
    "EnvironmentalSensingConfigurationDescriptor",
    "EnvironmentalSensingMeasurementData",
    "EnvironmentalSensingMeasurementDescriptor",
    "EnvironmentalSensingTriggerSettingData",
    "EnvironmentalSensingTriggerSettingDescriptor",
    "ExtendedPropertiesFlags",
    "ExternalReportReferenceData",
    "ExternalReportReferenceDescriptor",
    "FormatNamespace",
    "FormatType",
    "IMDTriggerSettingData",
    "IMDTriggerSettingDescriptor",
    "ManufacturerLimitsData",
    "ManufacturerLimitsDescriptor",
    "MeasurementDescriptionData",
    "MeasurementDescriptionDescriptor",
    "NumberOfDigitalsData",
    "NumberOfDigitalsDescriptor",
    "ObservationScheduleData",
    "ObservationScheduleDescriptor",
    "ProcessTolerancesData",
    "ProcessTolerancesDescriptor",
    "ReportReferenceData",
    "ReportReferenceDescriptor",
    "ReportType",
    "SCCDData",
    "SCCDFlags",
    "ServerCharacteristicConfigurationDescriptor",
    "TimeTriggerSettingData",
    "TimeTriggerSettingDescriptor",
    "TriggerCondition",
    "ValidRangeAndAccuracyData",
    "ValidRangeAndAccuracyDescriptor",
    "ValidRangeData",
    "ValidRangeDescriptor",
    "ValueTriggerSettingData",
    "ValueTriggerSettingDescriptor",
)
